INSERT INTO category VALUES(1,"BOOKS");
INSERT INTO category VALUES(2,"GAMES");
INSERT INTO category VALUES(3,"GROCERIES");
INSERT INTO category VALUES(4,"ELECTRONICS");
INSERT INTO category VALUES(5,"CLOTHES");
select * from category;
