-- create database ecommerce;
use ecommerce;

-- DROP SCHEMA ecommerce;
CREATE TABLE IF NOT EXISTS supplier (
SUPP_ID int NOT NULL PRIMARY KEY,
SUPP_NAME varchar(50) NOT NULL,
SUPP_CITY varchar(50) NOT NULL,
SUPP_PHONE varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer (
CUS_ID int NOT NULL PRIMARY KEY,
CUS_NAME varchar(20) NOT NULL,
CUS_PHONE varchar(10) NOT NULL,
CUS_CITY varchar(30) NOT NULL,
CUS_GENDER char
);

CREATE TABLE IF NOT EXISTS category(
CAT_ID int NOT NULL PRIMARY KEY,
CAT_NAME varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS product(
PRO_ID int NOT NULL PRIMARY KEY,
PRO_NAME varchar(20) NOT NULL DEFAULT "Dummy",
PRO_DESC varchar(60),
CAT_ID INT,
FOREIGN KEY (CAT_ID) REFERENCES category(CAT_ID)
);

CREATE TABLE IF NOT EXISTS supplier_pricing(
PRICING_ID int NOT NULL PRIMARY KEY,
PRO_ID INT,
FOREIGN KEY (PRO_ID) REFERENCES product(PRO_ID),
SUPP_ID INT,
FOREIGN KEY (SUPP_ID) REFERENCES supplier(SUPP_ID),
SUPP_PRICE int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders(
ORD_ID int NOT NULL PRIMARY KEY,
ORD_AMOUNT INT NOT NULL,
ORD_DATE DATE NOT NULL,
CUS_ID INT,
FOREIGN KEY (CUS_ID) REFERENCES customer(CUS_ID),
PRICING_ID INT,
FOREIGN KEY (PRICING_ID) REFERENCES supplier_pricing(PRICING_ID)
);

CREATE TABLE IF NOT EXISTS rating(
RAT_ID int NOT NULL PRIMARY KEY,
ORD_ID INT,
FOREIGN KEY (ORD_ID) REFERENCES orders(ORD_ID),
RAT_RATSTARS INT NOT NULL
);

show tables;

INSERT INTO rating values(1,101,4);
INSERT INTO rating values(2,102,3);
INSERT INTO rating values(3,103,1);
INSERT INTO rating values(4,104,2);
INSERT INTO rating values(5,105,4);
INSERT INTO rating values(6,106,3);
INSERT INTO rating values(7,107,4);
INSERT INTO rating values(8,108,4);
INSERT INTO rating values(9,109,3);
INSERT INTO rating values(10,110,5);
INSERT INTO rating values(11,111,3);
INSERT INTO rating values(12,112,4);
INSERT INTO rating values(13,113,2);
INSERT INTO rating values(14,114,1);
INSERT INTO rating values(15,115,1);
INSERT INTO rating values(16,116,0);

SELECT COUNT(CUSOMTER





