-- create database ecommerce;
use ecommerce;
-- DROP SCHEMA ecommerce;
CREATE TABLE IF NOT EXISTS supplier (
SUPP_ID int NOT NULL PRIMARY KEY,
SUPP_NAME varchar(50) NOT NULL,
SUPP_CITY varchar(50) NOT NULL,
SUPP_PHONE varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer (
CUS_ID int NOT NULL PRIMARY KEY,
CUS_NAME varchar(20) NOT NULL,
CUS_PHONE varchar(10) NOT NULL,
CUS_CITY varchar(30) NOT NULL,
CUS_GENDER char
);

CREATE TABLE IF NOT EXISTS category(
CAT_ID int NOT NULL PRIMARY KEY,
CAT_NAME varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS product(
PRO_ID int NOT NULL PRIMARY KEY,
PRO_NAME varchar(20) NOT NULL DEFAULT "Dummy",
PRO_DESC varchar(60),
CAT_ID INT,
FOREIGN KEY (CAT_ID) REFERENCES category(CAT_ID)
);

CREATE TABLE IF NOT EXISTS supplier_pricing(
PRICING_ID int NOT NULL PRIMARY KEY,
PRO_ID INT,
FOREIGN KEY (PRO_ID) REFERENCES product(PRO_ID),
SUPP_ID INT,
FOREIGN KEY (SUPP_ID) REFERENCES supplier(SUPP_ID),
SUPP_PRICE int DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders(
ORD_ID int NOT NULL PRIMARY KEY,
ORD_AMOUNT INT NOT NULL,
ORD_DATE DATE NOT NULL,
CUS_ID INT,
FOREIGN KEY (CUS_ID) REFERENCES customer(CUS_ID),
PRICING_ID INT,
FOREIGN KEY (PRICING_ID) REFERENCES supplier_pricing(PRICING_ID)
);

CREATE TABLE IF NOT EXISTS rating(
RAT_ID int NOT NULL PRIMARY KEY,
ORD_ID INT,
FOREIGN KEY (ORD_ID) REFERENCES orders(ORD_ID),
RAT_RATSTARS INT NOT NULL
);

show tables;







