INSERT INTO product VALUES(1, "GTA V","Windows 7 and above with i5 processor and 8GB RAM", 2);
INSERT INTO product VALUES(2, "TSHIRT","SIZE-L with Black, Blue and White variations", 5);
INSERT INTO product VALUES(3, "ROG LAPTOP","Windows 10 with 15inch screen, i7 processor, 1TB SSD", 4);
INSERT INTO product VALUES(4, "OATS","Highly Nutritious from Nestle", 3);
INSERT INTO product VALUES(5, "HARRY POTTER", "Best Collection of all time by J.K Rowling", 1);
INSERT INTO product VALUES(6, "MILK", "1L Toned MIlk", 3);
INSERT INTO product VALUES(7, "Boat Earphones","1.5Meter long Dolby Atmos", 4);
INSERT INTO product VALUES(8, "Jeans", "Stretchable Denim Jeans with various sizes and color", 5);
INSERT INTO product VALUES(9, "Project IGI", "compatible with windows 7 and above", 2);
INSERT INTO product VALUES(10, "Hoodie", "Black GUCCI for 13 yrs and above", 5);
INSERT INTO product VALUES(11, "Rich Dad Poor Dad", "Written by RObert Kiyosaki", 1);
INSERT INTO product VALUES(12, "Train Your Brain", "By Shireen Stephen", 1);
select * from product;